# Generated by Django 5.0.1 on 2024-12-13 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservasApp', '0004_alter_reserva_estado_reserva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='ID',
            new_name='id',
        ),
    ]
